# Generated by Django 6.0.4 on 2026-04-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('matricule', models.CharField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fonctions', models.CharField(choices=[('Etudiant', 'Etudiant'), ('Formateur', 'Formateur'), ('Employé', 'Employé')])),
            ],
        ),
    ]
