# Generated by Django 6.0.4 on 2026-04-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
