# Generated by Django 6.0.4 on 2026-04-28 07:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
        ('livres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_limite', models.DateField(default=datetime.datetime(2026, 5, 13, 7, 57, 13, 92489))),
                ('date_retour', models.DateField(null=True)),
                ('status', models.CharField(choices=[('En retard', 'En retard'), ('Retourné', 'Retourné')])),
                ('remarque', models.TextField()),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherents.adherent')),
                ('bibliothecaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ref_livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.livre')),
            ],
        ),
    ]
