# Generated by Django 6.0.4 on 2026-04-30 12:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0001_initial'),
        ('livres', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprunt',
            old_name='status',
            new_name='statut',
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_limite',
            field=models.DateField(default=datetime.datetime(2026, 5, 15, 15, 14, 42, 365295)),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='ref_livre',
            field=models.ForeignKey(limit_choices_to={'ref_livre__quatite__gte': 1}, on_delete=django.db.models.deletion.CASCADE, to='livres.livre'),
        ),
    ]
