# Generated by Django 6.0.4 on 2026-04-28 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprunt',
            old_name='status',
            new_name='statut',
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_limite',
            field=models.DateField(default=datetime.datetime(2026, 5, 13, 11, 31, 0, 916908)),
        ),
    ]
