# Generated by Django 6.0.4 on 2026-04-29 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0002_rename_status_emprunt_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_limite',
            field=models.DateField(default=datetime.datetime(2026, 5, 14, 5, 16, 15, 404080)),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='statut',
            field=models.CharField(choices=[('En retard', 'Ertrd'), ('Retourné', 'Rtrné')]),
        ),
    ]
