# Generated by Django 6.0.4 on 2026-04-29 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0003_alter_emprunt_date_limite_alter_emprunt_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_limite',
            field=models.DateField(default=datetime.datetime(2026, 5, 14, 5, 18, 56, 854417)),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='remarque',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='statut',
            field=models.CharField(choices=[('En retard', 'En retard'), ('Retourné', 'Retourné'), ('Non retourné', 'Non retourné')], default='Non retourné'),
        ),
    ]
