# Generated by Django 6.0.4 on 2026-04-29 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0004_alter_emprunt_date_limite_alter_emprunt_remarque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_limite',
            field=models.DateField(default=datetime.datetime(2026, 5, 14, 5, 20, 37, 433789)),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
    ]
