# Generated by Django 6.0.4 on 2026-05-02 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0006_alter_emprunt_bibliothecaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_limite',
            field=models.DateField(default=datetime.datetime(2026, 5, 17, 15, 45, 1, 999066)),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='remarque',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
