# Generated by Django 6.0.4 on 2026-04-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('reference', models.CharField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('auteur', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('Math', 'Mathématique'), ('Physique', 'Physique'), ('Littérature', 'Littérature'), ('Droit', 'Doit'), ("Memoire de fin d'étude", "Memoire de fin d'étude"), ('Thèse', 'Thèse')])),
                ('quantite', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
